bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'top' => 'homes#top'
  get 'home/about' => 'homes#about'

  get 'books' => 'books#index', as: 'books'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'

  get 'users' => 'users#index', as: 'users'
  get 'users/:id' => 'users#show', as: 'user'
  get 'users/:id/edit' => 'users#edit', as: 'edit_user'
  patch 'users/:id' => 'users#update', as: 'update_user'
end

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, {length: {maximum: 200}}
  validates :body, presence: true


end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, {length: {in: 2..20}}
  validates :introduction, {length: {maximum: 50}}
end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    @users = User.all
    if @book.save
      flash[:create_book] = 'You have created book successfully.'
      redirect_to book_path(@book.id)
    else
      render :index
    end

  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @users = User.all

  end

  def show
    @bookshow = Book.find(params[:id])
    @book = Book.new
    @user = User.find(@bookshow.user_id)

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      render :edit
    else
      redirect_to "/books"
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:update_book] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end

  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new

  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all

  end

  def edit
      user = User.find(params[:id])
    if user == current_user
      @user = User.find(params[:id])
      render :edit
    else
      @user = current_user
      redirect_to user_path(@user.id)
    end

  end

  def update
    @book = Book.new
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:update_user] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<p id="notice"></p>
    <div class='container'>
      <div class='row'>
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h1>Editing Book</h1>
          <%= form_with model:@book, url:update_book_path(@book.id),  local: true do |f| %>
            <div class="form-group">
              <label for="book_title">Title</label>
              <%= f.text_field :title %>
            </div>
            <div class="form-group">
              <label for="book_opinion">Opinion</label>
              <%= f.text_field :body %>
            </textarea>
            </div>
            <div class="form-group">
              <%= f.submit "Update Book", :class=>"btn btn-success" %>
            </div>
          <% end %>
          <%= link_to "Show", book_path(@book.id) %> |
          <%= link_to "Back", "/books" %>
        </div>
      </div>
    </div>

bookers2/app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

 <div class='container px-5 px-sm-0'>
    <div class='row'>
      <%= render 'users/left', user: @user, book: @book %>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
      <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
                  <% end %>
              </td>
              <td><%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
      <% end %>
          </tbody>
        </table>
      </div>
    </div>
</div>

bookers2/app/views/books/show.html.erb
<% if @book.errors.any? %>
    <%= @book.errors.count %>件のエラーが発生しました
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  <% flash.each do |message_type, message| %>
    <p id="notice"><%= message %></p>
  <% end %>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <%= render 'users/left', user: @user, book: @book %>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table table-hover table-inverse'>
        <tr>
          <td><%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg' %>
                <br><%= @user.name %>
              <% end %>
          </td>
          <td><%= link_to book_path(@bookshow.id) do %>
                <%= @bookshow.title %>
              <% end %>
          </td>
          <td>
            <%= @bookshow.body %>
          </td>
          <% if @user.id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@bookshow.id) %></td>
            <td><%= link_to "Destroy", destroy_book_path(@bookshow.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

bookers2/app/views/homes/about.html.erb
<p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>

bookers2/app/views/homes/top.html.erb
<% flash.each do |message_type, message| %>
  <p id="notice"><%= message %></p>
<% end %>

<p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
          <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
          <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>
              <div class="btn-wrapper col-10 mx-auto">
                <div class="row">
                  <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
                </div>
                    <div class="row">
                      <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
                    </div>
              </div>
        </div>
      </div>
    </div>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <script src="https://kit.fontawesome.com/88153c1aaa.js" crossorigin="anonymous"></script>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li><%= link_to "Home", user_path(current_user.id), :class=>"fas fa-home nav-link text-light" %></li>
            <li><a class="fas fa-users nav-link text-light" href="/users"> Users</a></li>
            <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>
            <li><a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a></li>
          <% else %>
            <li><a class="fas fa-home nav-link text-light" href="/"> Home</a></li>
            <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
            <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a></li>
            <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
    <%= yield %>
    <footer>
      <div class='container mt-5'>
  	    <div class='row'>
    	    <div class='mx-auto'>
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>
  </body>
</html>

bookers2/app/views/users/_left.html.erb
<div class='col-md-3'>
    <h2>User info</h2>
    <table class='table'>
      <tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'100x100' %></tr>
      <tr>
	      <th>name</th>
	      <th><%= user.name %></th>
      </tr>
      <tr>
	      <th>introduction</th>
	      <th><%= user.introduction %></th>
      </tr>
    </table>
      <div class='row'>
        <p><%= link_to "プロフィール編集", edit_user_path(user.id), :class=>"btn btn-outline-secondary btn-block fas fa-user-cog" %></p>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, url:books_path, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</lavel>
        <%= f.text_field :title %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</lavel>
        <%= f.text_area :body %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book', :class=>"btn btn-success" %>
      </div>
      <% end %>
  </div>

bookers2/app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<p id="notice"></p>
    <div class='container'>
      <div class='row'>
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h2>User info</h2>
          <%= form_with model:@user, local:true do |f| %>
            <div class="form-group">
              <label for="user_name">Name</label>
              <%= f.text_field :name %>
            </div>
            <div class="form-group">
              <label for="user_image">Image</label>
              <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
            </div>
            <div class="form-group">
              <label for="user_introduction">Introduction</label>
              <%= f.text_field :introduction %>
            </textarea>
            </div>
            <div class="form-group">
              <%= f.submit "Update User", :class=>"btn btn-secondary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

bookers2/app/views/users/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <%= render 'users/left', user: @user, book: @book %>
      <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <table class='table'>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= link_to user_path(user.id) do %>
                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
          </td>
          <td>名前：<%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
        <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

bookers2/app/views/users/show.html.erb
  <% if @book.errors.any? %>
    <%= @book.errors.count %>件のエラーが発生しました
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <% flash.each do |message_type, message| %>
    <p id="notice"><%= message %></p>
  <% end %>


  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <%= render 'users/left', user: @user, book: @book %>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(book.user_id) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
              </td><% end %>
              <td><%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
            </tr>
          <% end %>
        </tbody>
        </table>
      </div>
    </div>
  </div>
<%= paginate @books %>